### ISSUE TITLE
WLAN

### ISSUE THREAD

**Issue by Guenni75** [stnkl/FastLEDHub#16]
Hello.
Where are the WLan Settings???

**Comment by srwi** [comment]
FastLEDHub uses [WiFiManager](https://github.com/tzapu/WiFiManager) to manage wifi settings. Rather than instantiating a new WiFiManager instance you can access its settings via the existing instance like this:

    #include <ESPEssentials.h>
    ...
    ESPEssentials::Wifi.resetSettings();

For more information on how to use WiFiManager, please have a look [here](https://github.com/tzapu/WiFiManager).
